# Generated by Django 5.1.2 on 2024-12-15 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("brand_id", models.IntegerField(primary_key=True, serialize=False)),
                ("brand_name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=4)),
                ("images", models.CharField(max_length=50)),
                (
                    "brand_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="ecomStore.brand",
                    ),
                ),
            ],
        ),
    ]
