# Generated by Django 5.1.2 on 2025-01-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomStore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="brand_name",
            field=models.CharField(
                choices=[
                    ("CR", "Cleto Reyes"),
                    ("FR", "Fairtex"),
                    ("TW", "Twins"),
                    ("YK", "Yokkao"),
                ],
                max_length=10,
            ),
        ),
    ]
