# Generated by Django 5.1.2 on 2025-01-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomStore", "0002_alter_brand_brand_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.CharField(default="Input a color", max_length=20),
        ),
        migrations.AddField(
            model_name="product",
            name="product",
            field=models.CharField(
                choices=[("BG", "Boxing Gloves")], default="Input a product"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="brand_name",
            field=models.CharField(
                choices=[
                    ("CR", "Cleto Reyes"),
                    ("FR", "Fairtex"),
                    ("TW", "Twins"),
                    ("YK", "Yokkao"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=70),
        ),
    ]
