# Generated by Django 5.1.2 on 2025-01-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomStore", "0003_product_colors_product_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.CharField(max_length=100),
        ),
    ]
