# Generated by Django 5.1.2 on 2025-01-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomStore", "0006_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="number_of_purchases",
            field=models.IntegerField(default=0),
        ),
    ]
