# Generated by Django 5.1.2 on 2025-02-07 21:46

import django.db.models.deletion
import ecomStore.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomStore", "0007_product_number_of_purchases"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("cart_id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(default="First name (optional)")),
                ("last_name", models.CharField(default="Last name")),
                ("email", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("country_or_region", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=20)),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[ecomStore.models.Customer.format_phone_number],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ecomStore.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecomStore.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ecomStore.customer"
            ),
        ),
    ]
