# Generated by Django 5.1.2 on 2025-02-13 01:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecomStore", "0008_cart_customer_cartitem_cart_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="brand_id",
            new_name="brand",
        ),
    ]
