# Generated by Django 5.1.2 on 2025-03-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomStore", "0010_alter_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
