# Generated by Django 5.1.2 on 2025-03-05 23:44

import ecomStore.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomStore", "0012_alter_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ImageField(upload_to=ecomStore.models.product_upload_to),
        ),
    ]
