# Generated by Django 5.1.2 on 2025-04-07 21:05

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomStore", "0013_alter_product_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=django.utils.timezone.now,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.UUIDField(default=uuid.UUID, editable=False, unique=True),
        ),
    ]
