# Generated by Django 5.1.2 on 2025-04-07 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecomStore", "0013_alter_product_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
