# Generated by Django 5.1.2 on 2025-04-07 21:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomStore", "0014_cart_created_at_cart_id_alter_cart_cart_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="id",
        ),
        migrations.AddField(
            model_name="cart",
            name="cid",
            field=models.AutoField(
                default=django.utils.timezone.now, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecomStore.customer",
            ),
        ),
    ]
