# Generated by Django 5.1.2 on 2025-04-07 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecomStore", "0015_remove_cart_id_cart_cid_alter_cart_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="cid",
            new_name="id",
        ),
    ]
