# Generated by Django 5.1.2 on 2025-04-07 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecomStore", "0017_alter_cart_cart_id"),
        ("ecomStore", "0017_cart_cartitem"),
    ]

    operations = []
